### ISSUE TITLE
Not sure this is a bug...

### ISSUE THREAD

**Issue by timlem** [ShepherdDev/rock-survey-system#1]
Hey Daniel...

I need to have a survey that is public facing and send people a link to that survey and I'd like to use a token generator to automatically log them in. I'm doing this based on the documentation from wistia plugin.

https://hf.church/page/754?SurveyId=7?rckipid={{ Person | PersonTokenCreate }} won't work. I'm wondering if there is a way I can force the survey on a page without the '?SurveyId=7'. Or at least I'm assuming those two variables in the url are the issue.

**Comment by cabal95** [comment]
I think you want to use

`https://hf.church/page/754?SurveyId&rckipid={{ Person | PersonTokenCreate }}`

Note the change of the second `?` to a `&`.

**Comment by timlem** [comment]
Got this error:
NullReferenceException in Rock

Message
Object reference not set to an instance of an object.
Stack Trace
   at Rock.Web.PageReference.BuildUrl(Boolean removeMagicToken)
   at Rock.Web.UI.RockPage.ProcessImpersonation(RockContext rockContext)
   at Rock.Web.UI.RockPage.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by timlem** [comment]
used this https://hf.church/page/754?7&rckipid={{ Person | PersonTokenCreate }}

**Comment by timlem** [comment]
oh wait I think I see. My fault... trying again

**Comment by timlem** [comment]
ok got it working. Sorry to bug ya Daniel. Thank you for being awesome!
