### ISSUE TITLE
HTML Code in Survey Response

### ISSUE THREAD

**Issue by timrust85** [ShepherdDev/rock-survey-system#14]
![Screenshot 2021-09-10 101649](https://user-images.githubusercontent.com/90466260/132876993-d2cee742-a8af-4ba4-83c9-4429cbd6c2f3.png)
When we look at the survey response detail page, an email address shows up with HTML, as if it's trying to create a link.

**Comment by raufrecht** [comment]
The rating field type does the same thing
![image](https://user-images.githubusercontent.com/45696078/146798282-e4f49866-f0b1-4757-b8dd-88a9d4c838bf.png)

**Comment by cabal95** [comment]
This should be fixed in Version 2.6.0 of the plugin which should be released later this week in the Rock Shop.
