### ISSUE TITLE
Retake Survey

### ISSUE THREAD

**Issue by stevelipinski** [ShepherdDev/rock-survey-system#15]
Is there an existing way to support a Person only having a single Survey result?  e.g., if I take the survey today, it stores my results that I took it.  However, if I (same Person) re-take the survey tomorrow, it will record another, separate result.
Is it possible for either - the retake is not allowed if an existing Result exists and/or the retake is allowed, but overrides the previous responses?

**Comment by cabal95** [comment]
@stevelipinski i don’t think there is a way to do that automatically. But one option that comes to mind is to create a workflow to do it. The survey can be configured to run a specific workflow whenever it is submitted. With that workflow you could run a sql statement to delete any past SurveyResult objects for that Person/Survey.

**Comment by treusch** [comment]
@cabal95 - is there a way to allow a person to update their answers for an existing survey if we want to give them a chance to retake it and correct their wrong answers?

**Comment by cabal95** [comment]
@treusch There is not.
