### ISSUE TITLE
Unable to load MEF and Could not load file or assembly X937

### ISSUE THREAD

**Issue by treusch** [ShepherdDev/rock-survey-system#16]
We are getting the following error a lot lately in our Rock Exceptions:

Unable to load MEF from com.shepherdchurch.ImageCashLetter, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

That error is a parent item of the following error:
Could not load file or assembly 'X937, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

We are on version 11.4 of Rock. Any help would be greatly appreciated. Thanks!

**Comment by cabal95** [comment]
Hi @treusch, I think somebody already may have spoke to you about this.  But that library is not one that is really supported by us. Meaning, we wrote it primarily for internal use but we made the code available for partners to use. I know at least one partner was using it to provide the same services to other churches. It's part of a package to allow you to do digital deposits of tithe checks directly to your bank.

The error it is giving is that it is missing one of the required dependencies, a file called X937.dll. If you are not doing digital check deposits then you can probably just delete the com.shepherdchurch.ImageCashLetter.dll from your bin\ folder. If you are, you would need to reach out to the partner that helped you get it setup and going.
