### ISSUE TITLE
Excel export of results not filling in 'Completed By' field

### ISSUE THREAD

**Issue by atorrance** [ShepherdDev/rock-survey-system#3]
We made a survey which was sent to specific Person Tokens. The 'Completed By' field in Rock is showing correctly who completed the survey but the column is completely empty in the Excel export. 

![image](https://user-images.githubusercontent.com/34725020/54930959-90cc4580-4eee-11e9-9d8a-6ed6025169f9.png)

![image](https://user-images.githubusercontent.com/34725020/54931014-a6da0600-4eee-11e9-9f48-fac2b67513d9.png)

**Comment by cabal95** [comment]
Thanks for the report, looking into this.

**Comment by cabal95** [comment]
This appears to be an issue in the Rock core library. It should be fixed in v9.
