### ISSUE TITLE
Filters for Survey Charts

### ISSUE THREAD

**Issue by sballardSummit** [ShepherdDev/rock-survey-system#6]
We love the Survey plugin! Would love to add the same filter options to the charts view that are present on the results page. Then once certain filters are used, the charts update based on filter options like the results page does. Right now, the team is filtering the results page and exporting them to Excel to build their own charts.

**Example** We want to filter the chart to only show Campus A answers those with kids vs. Campus A answers those without kids.

**Comment by cabal95** [comment]
Filtering for charts page will be available in release 2.3.0.
