### ISSUE TITLE
Showing Person names as clickable links

### ISSUE THREAD

**Issue by motihat** [ShepherdDev/rock-survey-system#8]
The Survey plug-in seems really easy to use.  I was trying to use it for survey to be completed by logged-in users only. One thing I would like is to be able to click on the person name in "Completed By" field to jump to his/her record in Rock.  Same is true if we have a survey question where the response field is of type "Person".  
Currently the survey results, both in list and detail view, only show the First and Last names for Person Fields and that does not always narrow it down enough as there can be more than one person in database with matching First and Last name.
Is there currently a way to jump to the correct Person record in rock from a response field of type person displayed in survey results?

**Comment by cabal95** [comment]
Will be implemented in next plugin release, version 2.4.0.
