### ISSUE TITLE
Error when attempting to filter Survey Results

### ISSUE THREAD

**Issue by danielmilner** [ShepherdDev/rock-survey-system#9]
We're getting the following error after clicking on the "Apply Filter" button while viewing the Survey Results. If we refresh the page, the filter works and we don't see the error, but it will pop back up as soon as we click on the "Apply Filter" button again. 

Any idea what could be causing this?

![image](https://user-images.githubusercontent.com/151375/87985421-6eb9e780-ca90-11ea-907e-2925d003b0b9.png)

**Comment by cabal95** [comment]
@danielmilner What version of Rock are you on? That sounds like it might be related to an older issue in Rock core that was fixed. It had to do with the filters throwing errors with attributes that had long names (which worklows and surveys often did).

**Comment by danielmilner** [comment]
It looks like they are on 10.1

**Comment by cabal95** [comment]
Okay, it looks like that is the same issue and it was fixed in 10.2: SparkDevNetwork/Rock#3971

The issue says fixed in 9.5, but that was never released. I checked the release notes and this fix shows up on 10.2.

**Comment by danielmilner** [comment]
Thank you @cabal95. I will let them know that they need to update Rock.
